spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

endpoints:
  post:
    by-user: http://localhost:8082/posts?userId=
  comment:
    all: http://localhost:8082/comments
  photo:
    all: http://localhost:8082/photos
  user:
    all: http://localhost:8082/users
  album:
    all: http://localhost:8082/albums